name: Docker Build, Test, and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Generate serial number
      id: serial
      run: echo "::set-output name=num::$(date +%Y%m%d%H%M%S)"

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        load: true
        tags: ${{ secrets.DOCKER_REPO_NAME }}:${{ steps.serial.outputs.num }}

    - name: Test container
      run: |
        docker run ${{ secrets.DOCKER_REPO_NAME }}:${{ steps.serial.outputs.num }} python -c "print('Container test successful')"

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push to DockerHub
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPO_NAME }}:${{ steps.serial.outputs.num }}